#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

struct mazePoint {
	int NPath;
	int SPath;
	int EPath;
	int WPath;
};

void blackLineTrack(bool leftLine) {
	// if line on the left
	if (leftLine) {
		if (getColorReflected(colorSensor) < 15)  {
			setMotorSpeed(leftMotor, -20);
			setMotorSpeed(rightMotor, 0);
		}
		else {
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, -20);
		}
	}
	// if line on the right
	else {
		if (getColorReflected(colorSensor) < 15)  {
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, -10);
		}
		else {
			setMotorSpeed(leftMotor, -10);
			setMotorSpeed(rightMotor, 0);
		}
	}
}

void yellowLineTrack() {
		if (getColorReflected(colorSensor) > 40) {
			setMotorSpeed(leftMotor, -10);
			setMotorSpeed(rightMotor, 0);
		}
		else {
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, -10);
		}
}

bool leftScan (bool turn) {
	bool leftLine = false;
	int encoderTarget = 100;
	while (getMotorEncoder(armMotor) < encoderTarget) {
		setMotorSpeed(armMotor, 5);
		//&& getMotorEncoder(armMotor) < -45
        if (turn) {
            if (getColorReflected(colorSensor) < 15 && getMotorEncoder(armMotor) > 45) {
                leftLine = true;
            }
        }
        else {
            if (getColorReflected(colorSensor) < 15) {
			    leftLine = true;
		    }
        }
	}
	encoderTarget = 0;
	while (getMotorEncoder(armMotor) > encoderTarget) {
		setMotorSpeed(armMotor, -5);
		if (getColorReflected(colorSensor) < 15 && getMotorEncoder(armMotor) > 45) {
			leftLine = true;
		}
	}
	setMotorSpeed(armMotor, 0);
	return leftLine;
}

bool rightScan (bool turn) {
	bool rightLine = false;
	int encoderTarget = -100;
	while (getMotorEncoder(armMotor) > encoderTarget) {
		setMotorSpeed(armMotor, -5);
		//&& getMotorEncoder(armMotor) < -45
        if (turn) {
            if (getColorReflected(colorSensor) < 15 && getMotorEncoder(armMotor) < -45) {
                rightLine = true;
            }
        }
        else {
            if (getColorReflected(colorSensor) < 15) {
                rightLine = true;
            }
        }
	}
	encoderTarget = 0;
	while (getMotorEncoder(armMotor) < encoderTarget) {
		setMotorSpeed(armMotor, 5);
		if (turn) {
            if (getColorReflected(colorSensor) < 15 && getMotorEncoder(armMotor) < -45) {
                rightLine = true;
            }
        }
        else {
            if (getColorReflected(colorSensor) < 15) {
                rightLine = true;
            }
        }
	}
	setMotorSpeed(armMotor, 0);
	return rightLine;
}

// Line on the left: 0
// Line on the right: 1
// Line on the both: 2
// no line: -1
bool findLine() {
	bool leftLine = false;
	bool rightLine = false;
	if (leftScan()) {
		leftLine = true;
	}
	if (rightScan()) {
		rightLine = true;
	}
	if (leftLine && !rightLine) {
		return true;
	}
	else if (!leftLine && rightLine) {
		return false;
	}
	else {
		return false;
	}
}

void firstMove() {
	//bool left = findLine();
	bool left = true;
	int change = 400;
	int encoderTarget = getMotorEncoder(rightMotor) - change;
	while (getMotorEncoder(rightMotor) > encoderTarget) {
		blackLineTrack(left);
	}
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
}

void moveStraight(int direction) {
	bool left = findLine();
	//bool left = true;
	int change = 600;
	int thresh = 400;
	int encoderTarget = getMotorEncoder(rightMotor) - change;
	while (getMotorEncoder(rightMotor) > encoderTarget - thresh) {
		blackLineTrack(left);
		if (abs(getMotorEncoder(rightMotor) - encoderTarget) < thresh) {
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			break;
		}
	}

	while (getMotorEncoder(rightMotor) > encoderTarget) {
		setMotorSpeed(leftMotor, -20);
		setMotorSpeed(rightMotor, -20);
		if (abs(getMotorEncoder(rightMotor) - encoderTarget) < thresh) {
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			if (direction == -1) {
				if(leftScan()) break;
			}
			else if (direction == 1) {
				if(rightScan()) break;
			}
			thresh -= 150;
		}
	}

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
}

void leftTurn() {
	int change = 100;
	int encoderTarget = getMotorEncoder(rightMotor) - change;
	while (getMotorEncoder(rightMotor) > encoderTarget) {
		setMotorSpeed(leftMotor, -10);
		setMotorSpeed(rightMotor, -10);
	}
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	change = 300;
	encoderTarget = getMotorEncoder(rightMotor) - change;
	while (getMotorEncoder(rightMotor) > encoderTarget) {
		setMotorSpeed(rightMotor, -10);
	}
	setMotorSpeed(rightMotor, 0);
}

void rightTurn() {
	int change = 100;
	int encoderTarget = getMotorEncoder(leftMotor) - change;
	while (getMotorEncoder(leftMotor) > encoderTarget) {
		setMotorSpeed(leftMotor, -10);
		setMotorSpeed(rightMotor, -10);
	}
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	change = 150;
	encoderTarget = getMotorEncoder(leftMotor) - change;
	while (getMotorEncoder(leftMotor) > encoderTarget) {
		setMotorSpeed(leftMotor, -10);
        setMotorSpeed(rightMotor, 10);
	}
	setMotorSpeed(leftMotor, 0);
}

task main()
{
	rightTurn();
	//firstMove();
	//moveStraight(1);
	//rightTurn();
	//moveStraight(-1);
	//leftTurn();
	//moveStraight(1);
	//rightTurn();
	//moveStraight(-1);
	//leftTurn();
}

